### ISSUE TITLE
Wrong day for date

### ISSUE THREAD

**Issue by edmechem** [haoict/weather-plus#1]
Perhaps a time zone issue?
![F3FDFCD1-664B-4AEC-983D-E7DFE630D4D6](https://user-images.githubusercontent.com/171138/86222682-6cbcd280-bb3b-11ea-8ed5-a8a2e894d69e.png)

**Comment by haoict** [comment]
I bet it's a bug from Weather app itself. Try uninstall/disable the tweak and you still see wrong DOW
It will be correct around 4-5AM.
